apiVersion: v1
kind: Secret
metadata:
  name: microservice-db-secret
  namespace: anwb-playground

type: Opaque
stringData:
  connectionString: "Server=microservice-db-service;Database=microservicedb;Integrated Security=true;Pooling=true;User ID=postgres;"
